variables:
    GIT_SUBMODULE_STRATEGY: recursive


stages:
    - build
    - test
    - example
    - trigger


default:
    tags:
        - fast-dockers
    image: docker.io/trasioteam/taref-dev:keystone

suit_build:
    stage: build
    script:
        - mkdir suit/build
        - cd suit/build
        - cmake ..
        - make

suit_test:
    script:
        - echo OK

suit_example:
    stage: example
    script:
        - mkdir suit/build
        - cd suit/build
        - cmake ..
        - make
        - ./example/dump ../example/manifests/teep-I-D/ex1.suit
        - ./example/dump ../example/manifests/teep-I-D/ex2.suit
        - ./example/dump ../example/manifests/teep-I-D/ex3.suit
        - ./example/run-install ../example/manifests/teep-I-D/ex1.suit
        - ./example/run-install ../example/manifests/teep-I-D/ex2.suit
        - ./example/run-install ../example/manifests/teep-I-D/ex3.suit

teep_build:
    stage: build
    script:
        - sudo apt-get install -y libcap-dev
        - export TEE=pc
        - make

teep_test:
    stage: test
    services:
        - name: docker.io/trasioteam/tamproto:latest
          alias: tamproto
    script:
        - TAMIP=`python3 -c 'import socket;print(socket.gethostbyname("tamproto"))'`
        - export TAM_URL="http://$TAMIP:8888"
        - sudo apt-get install -y libcap-dev
        - export TEE=pc
        - make
        - make run-sample-session

teep_test_keystone:
    stage: test
    image: docker.io/trasioteam/taref-dev:keystone
    services:
        - name: docker.io/trasioteam/tamproto:latest
          alias: tamproto
    script:
        - sudo apt-get install -y e2tools
        - TAMIP=`python3 -c 'import socket;print(socket.gethostbyname("tamproto"))'`
        - export TAM_URL="http://$TAMIP:8888"
        - make
        - make run-sample-session | tr -d "\r"

teep_test_optee:
    stage: test
    image: docker.io/trasioteam/taref-dev:optee
    services:
        - name: docker.io/trasioteam/tamproto:latest
          alias: tamproto
    script:
        - TAMIP=`python3 -c 'import socket;print(socket.gethostbyname("tamproto"))'`
        - export TAM_URL="http://$TAMIP:8888"
        - make
        - make run-sample-session | tr -d "\r"

teep_test_sgx:
    stage: test
    image: docker.io/trasioteam/taref-dev:sgx
    services:
        - name: docker.io/trasioteam/tamproto:latest
          alias: tamproto
    script:
        - TAMIP=`python3 -c 'import socket;print(socket.gethostbyname("tamproto"))'`
        - export TAM_URL="http://$TAMIP:8888"
        - export MACHINE=SIM
        - make
        - make run-sample-session | tr -d "\r"


### DOXYGEN - START ###
teep_doxygen:
    stage: build
    image: docker.io/trasioteam/taref-dev:doxygen
    script:
        - make docs
    artifacts:
        paths:
            - docs/teep-device.pdf
            - docs/teep-device_readme_html.tar.gz
        expire_in: 1 week

### DOXYGEN - START ###

trigger_docker-teep-dev:
    variables:
        TOKEN: 0b8ade51abfe0f4a0bf3d502a5d3b8
    stage: trigger
    tags:
        - shell117
    script:
        - "curl -X POST --fail -F token=${TOKEN} -F ref=main https://192.168.100.100/api/v4/projects/133/trigger/pipeline"
