#pragma once

#define TEEP_AGENT_TA_WRAP_MESSAGE 1
#define TEEP_AGENT_TA_SIGN_MESSAGE 11
#define TEEP_AGENT_TA_ENCRYPT_MESSAGE 12
#define TEEP_AGENT_TA_UNWRAP_MESSAGE 2
#define TEEP_AGENT_TA_VERIFY_MESSAGE 21
#define TEEP_AGENT_TA_DECRYPT_MESSAGE 22
#define TEEP_AGENT_TA_INSTALL 101
#define TEEP_AGENT_TA_DELETE 102
#define TEEP_AGENT_TA_UNWRAP_TA_IMAGE 301
#define TEEP_AGENT_TA_EXIT 1000
